In [27]:
import numpy as np
from importlib import reload
import operator

In [28]:
import kNN

In [57]:
reload(kNN)
X, Y = kNN.CreateDataSet()
X

array([[ 1. ,  1.1],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 0. ,  0.1]])

In [52]:
x_test = np.array([0.3, 0.1])
kNN.kNN(x_test, X, Y, kNN.dist, 2)

'B'

In [53]:
X

array([[ 1. ,  1.1],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 0. ,  0.1]])

In [56]:
np.max(X, axis=0)

array([ 1. ,  1.1])

In [58]:
kNN.normalize(X)

array([[ 1.        ,  1.        ],
       [ 1.        ,  0.90909091],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.09090909]])